In [2]:
import pandas as pd

In [3]:
#Dataset
df=pd.read_csv('https://raw.githubusercontent.com/krishnaik06/Diabetes-Prediction/master/data/pima-data.csv')
df.head()

num_preg  glucose_conc  diastolic_bp  thickness  insulin   bmi  diab_pred  \
0         6           148            72         35        0  33.6      0.627   
1         1            85            66         29        0  26.6      0.351   
2         8           183            64          0        0  23.3      0.672   
3         1            89            66         23       94  28.1      0.167   
4         0           137            40         35      168  43.1      2.288   

   age    skin  diabetes  
0   50  1.3790      True  
1   31  1.1426     False  
2   32  0.0000      True  
3   21  0.9062     False  
4   33  1.3790      True

In [4]:
df.shape

(768, 10)

In [5]:
df.isnull().sum()

num_preg        0
glucose_conc    0
diastolic_bp    0
thickness       0
insulin         0
bmi             0
diab_pred       0
age             0
skin            0
diabetes        0
dtype: int64

In [6]:
y_df=df[['diabetes']]
y_df=pd.get_dummies(y_df,drop_first=True)

In [7]:
y_df.head()

diabetes
0      True
1     False
2      True
3     False
4      True

In [8]:
y_df['diabetes']=y_df['diabetes'].astype('object')

In [9]:
y_df=pd.get_dummies(y_df,drop_first=True)

In [10]:
y_df.head()

diabetes_True
0              1
1              0
2              1
3              0
4              1

In [11]:
y_df.shape

(768, 1)

In [12]:
X=df.iloc[:,:9]

In [13]:
X.shape

(768, 9)

In [14]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [15]:
X=np.asarray(X)
X.shape

(768, 9)

In [16]:
X[:5]

array([[6.0000e+00, 1.4800e+02, 7.2000e+01, 3.5000e+01, 0.0000e+00,
        3.3600e+01, 6.2700e-01, 5.0000e+01, 1.3790e+00],
       [1.0000e+00, 8.5000e+01, 6.6000e+01, 2.9000e+01, 0.0000e+00,
        2.6600e+01, 3.5100e-01, 3.1000e+01, 1.1426e+00],
       [8.0000e+00, 1.8300e+02, 6.4000e+01, 0.0000e+00, 0.0000e+00,
        2.3300e+01, 6.7200e-01, 3.2000e+01, 0.0000e+00],
       [1.0000e+00, 8.9000e+01, 6.6000e+01, 2.3000e+01, 9.4000e+01,
        2.8100e+01, 1.6700e-01, 2.1000e+01, 9.0620e-01],
       [0.0000e+00, 1.3700e+02, 4.0000e+01, 3.5000e+01, 1.6800e+02,
        4.3100e+01, 2.2880e+00, 3.3000e+01, 1.3790e+00]])

In [17]:
#Standardization
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.69289057,
         0.20401277,  0.46849198,  1.4259954 ,  0.90726993],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.69289057,
        -0.68442195, -0.36506078, -0.19067191,  0.53090156],
       [ 1.23388019,  1.94372388, -0.26394125, -1.28821221, -0.69289057,
        -1.10325546,  0.60439732, -0.10558415, -1.28821221],
       [-0.84488505, -0.99820778, -0.16054575,  0.15453319,  0.12330164,
        -0.49404308, -0.92076261, -1.04154944,  0.15453319],
       [-1.14185152,  0.5040552 , -1.50468724,  0.90726993,  0.76583594,
         1.4097456 ,  5.4849091 , -0.0204964 ,  0.90726993]])

In [21]:
from sklearn.model_selection import train_test_split
X,X_test,Y,y_test = train_test_split( X, Y, test_size=0.2, random_state=4)

In [37]:
X_test.shape

(9, 154)

In [36]:
X_test=X_test.T

In [22]:
X=X.T

In [23]:
X.shape

(9, 614)

In [24]:
X[:5]

array([[-1.14185152, -0.84488505, -0.54791859, ...,  0.63994726,
        -0.54791859, -0.54791859],
       [-1.68674498, -1.27988209, -0.49745345, ..., -0.43485916,
        -1.43636781, -0.43485916],
       [ 0.35643175, -0.729221  ,  0.304734  , ...,  0.97680475,
        -0.26394125,  0.25303625],
       [-1.28821221, -1.28821221, -1.28821221, ..., -1.28821221,
         0.21726125,  0.59362962],
       [-0.69289057, -0.69289057, -0.69289057, ..., -0.69289057,
        -0.2153313 ,  0.17539902]])

In [18]:
Y=np.asarray(y_df)
Y.shape

(768, 1)

In [19]:
Y[:5]

array([[1],
       [0],
       [1],
       [0],
       [1]], dtype=uint8)

In [40]:
y_test.shape

(1, 154)

In [39]:
y_test=y_test.T

In [25]:
Y=Y.T

In [26]:
Y.shape

(1, 614)

In [27]:
Y[:5]

array([[0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
        1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 

In [28]:
##Sigmoid Function
def sigmoid(z):
    s=1/(1+np.exp(-z))
    return s

In [29]:
# z=w.T(x)+b Initialise parameters w &b
def initialize_with_zeros(dim):
    w=np.zeros((dim,1))
    b=0.
    return w, b

In [30]:
#Forward & Back Propogation
def propagate(w, b, X, Y):
    m=X.shape[1]
    A = sigmoid(np.dot(w.T, X) + b)
    cost = -1/m*(np.sum(Y*np.log(A) + (1-Y)*np.log(1-A)))
    # Back
    dw = 1/m*(np.dot(X, ((A-Y).T)))
    db = 1/m*(np.sum(A-Y))
    cost = np.squeeze(np.array(cost))
    grads = {"dw": dw,
             "db": db}
    return grads, cost

In [43]:
def optimize(w, b, X, Y, num_iterations=100, learning_rate=0.009, print_cost=False):
    costs = []
    for i in range(num_iterations):
        grads, cost = propagate(w, b, X, Y)
        dw = grads["dw"]
        db = grads["db"]
        w = w - learning_rate*dw
        b = b - learning_rate*db
        if i % 100 == 0:
            costs.append(cost)
        if print_cost:
            print ("Cost after iteration %i: %f" %(i, cost))
    params = {"w": w,
              "b": b}
    
    grads = {"dw": dw,
             "db": db}
    
    return params, grads, costs

        

In [32]:
def predict(w, b, X):
    m = X.shape[1]
    Y_prediction = np.zeros((1, m))
    w = w.reshape(X.shape[0], 1)
    A = sigmoid(np.dot(w.T, X)+ b)
    for i in range(A.shape[1]):
        Y_prediction[0][i] = 1 if A[0][i]>0.5 else 0
    return Y_prediction

In [34]:
def model(X_train, Y_train, X_test, Y_test, num_iterations=2000, learning_rate=0.5, print_cost=False):
    w, b = initialize_with_zeros(X_train.shape[0])
    parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost = False)
    w = parameters["w"]
    b = parameters["b"]
    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)
    if print_cost:
        print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
        print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))
    
    d = {"costs": costs,
         "Y_prediction_test": Y_prediction_test, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    return d

In [44]:
logistic_regression_model = model(X, Y, X_test,y_test, num_iterations=2000, learning_rate=0.005, print_cost=True)

train accuracy: 76.8729641693811 %
test accuracy: 77.92207792207792 %
